
## Covid 19

```{r}
# econDV2::Object(vaccine)
vaccine$source[[1]] <- "https://api.1922.gov.tw/vab-opendata/api/waitingAmountByCityAge5"
vaccine$source[[2]] <- "https://data.gov.tw/dataset/144586"
vaccine$data$original <- jsonlite::fromJSON(vaccine$source[[1]])
source("support/covid19.R")
vaccine$data$cleanup <-
  get_vaccineDF_aggregate(vaccine$data$original)
# vaccine$save()
```

```{r}
vaccine = readRDS("data/vaccine.Rds")
```


```{r}
covid19_global_cases_and_deaths <- read_csv("https://od.cdc.gov.tw/eic/covid19/covid19_global_cases_and_deaths.csv")

```

```{r}
econDV2::Object(covid19)
covid19$source[[1]] <- "https://github.com/CSSEGISandData/COVID-19/raw/master/archived_data/archived_time_series/time_series_19-covid-Confirmed_archived_0325.csv"
covid19$data$original <-
  readr::read_csv(
    covid19$source[[1]]
  )
covid19$data$original |> select(-c(1,3,4)) -> covid19$data$cleanup
covid19$data$cleanup |> #names() |> head()
  tidyr::pivot_longer(
    cols=-1,
    names_to = "date",
    values_to = "confirmed_cases"
  ) |>
  mutate(
    date=lubridate::mdy(date)
  ) -> covid19$data$cleanup
covid19$data$cleanup$`Country/Region` |> unique() |> sort(decreasing = T)

covid19$data$cleanup |> #class()
  dplyr::filter(
    `Country/Region` %in% c("Japan", "Italy", 'Taiwan*', "US", "Singapore")
  )  -> covid19$data$filtered
covid19$save()
.df = covid19$data$filtered

```


```{r}
covid19=readRDS("data/covid19.Rds")
econDV2::Object(ggplot5)

ggplot5$data$highlighted <- covid19$data$filtered
ggplot5$data$background <- covid19$data$cleanup
ggplot5$data$highlighted$date |> range(na.rm=T)

ggplot5$base <- function()
{
  ggplot(data=ggplot5$data$highlighted)
}
ggplot5$geom_highlighted <- function()
{
  geom_line(
    aes(
      x=date,
      y=confirmed_cases,
      color=`Country/Region`
    )
  )
}
ggplot5$base() + ggplot5$geom_highlighted()
```

