

```{r}
ggplot(data=datax)+
  geom_...some_version

ggplot(data=datay)+
  geom_...some_version

ggplot(data=datay)+
  geom_..(data=datax)+geom...
```

```{r}
plot = new.env()

# static member
plot$data3 = {
  googlesheets4::gs4_deauth()
  googlesheets4::read_sheet(
    "https://docs.google.com/spreadsheets/d/1lkts4hLkrAFAobONFXiEjgDnuUmXKci6YF--vg1pC1s/edit?usp=sharing",
    sheet = "data 3"
  )}

# active member: the result depends on other member's status when called
plot$graph1 = function(){
  library(ggplot2)
  ggplot(data = plot$data3) +
   geom_point(
    mapping = aes(y = Characteristic, x = `Total Effect`, fill = Country, size = Population),
    shape = 21,
    alpha = 0.5
  ) +
  geom_point(
    mapping = aes(y = Characteristic, x = `Total Effect`, color = Country)
  )
}

plot$data3
plot$graph1()
```

Adding more members to the environment:
```{r}
# data3max 
plot$data3max = {
  library(dplyr)
  plot$data3 |>
    group_by(Characteristic) |>
    summarise(
      max = max(`Total Effect`)
    ) |>
    ungroup() }

# graph2
plot$graph2 = function(){
  plot$graph1()+
    geom_segment(
      data = plot$data3max,
      mapping = aes(x = 0, xend = max, y = Characteristic, yend = Characteristic)
    )
}

plot$data3 |> filter(Country!="a") -> plot$data3
plot$graph2()
```

```{r}
saveRDS(plot, "data3plot.Rds")
```


## restart 

```{r}
plot=readRDS("data3plot.Rds")
plot$data3
plot$graph1
```

## creatre active source member

```{r}
plot$createData3 = function(){
    googlesheets4::gs4_deauth()
    googlesheets4::read_sheet(
      "https://docs.google.com/spreadsheets/d/1lkts4hLkrAFAobONFXiEjgDnuUmXKci6YF--vg1pC1s/edit?usp=sharing",
      sheet = "data 3"
    ) -> plot$data3 # due to environment's mutability
    }

plot$data3$Country |> unique()
plot$createData3()
plot$data3$Country |> unique()
plot$graph1()
plot$graph2()

```

```{r}
ll=list()
ll$d=1
ll$graph = function() ll$d*3
ll$d
ll$graph()
ll$d=5
ll$graph()
ll$createD2 = function() ll$d +3 -> ll$d2
ll$createD2()
```

# geom_blank

```{r}
plot$graph1
ggplot(data = plot$data3) +
  geom_point(
      mapping = aes(y = Characteristic, x = `Total Effect`, color = Country)
    )+
     geom_blank(
      mapping = aes(y = Characteristic, x = `Total Effect`, fill = Country, size = Population),
      shape = 21,
      alpha = 0.5
    ) 
```


















